## Numpy

In [ ]:
import numpy as np  # numeric python
l1=[0,1,2,3,4,5]
np1=np.array(l1)
print(np1)
print(np1.shape) # gets the shape of an array


[0 1 2 3 4 5]
(6,)


In [ ]:
np2=np.arange(10) # type of a range fun
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np2=np.arange(10,2,-1)
print(np2)

[10  9  8  7  6  5  4  3]


In [ ]:
np3=np.zeros(3)
np3

array([0., 0., 0.])

In [ ]:
np3=np.zeros((2,10))
np3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.full((10),6)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [ ]:
np.full((2,10),6)

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

## Slicing of numpy array

In [ ]:
np1=np.arange(0,10)
print(np1)
np1[1:5]

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4])

In [ ]:
np1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
np1[-3:-1]

array([7, 8])

In [ ]:
np2=[np.arange(0,10),np.arange(0,10)]
np2

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [ ]:
np2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
np2[1,3]

9

In [ ]:
np2[0:1,0:3]  # np2[rows , rows ka slicing]

array([[1, 2, 3]])

In [ ]:
np2[0:2,3:4]

array([[4],
       [9]])

## Mathematical Operation

In [ ]:
import numpy as np
# Square Root
n1=np.array([0,1,2,3,4,5,6,7,8,9])
np.sqrt(n1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# return Absolute value : remove negative sign
n1=np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
np.absolute(n1)

array([3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# exponents
print(np.exp(n1))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [ ]:
# Max and Min
print(np.max(n1))
print(np.min(n1))

9
-3


In [ ]:
# Sign Positive and Negative
print(np.sign(n1))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


In [ ]:
# Trigonomentry , Logrithm
print(np.sin(n1))
print(np.log(n1))

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
[       nan        nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154
 2.19722458]


<ipython-input-18-215be5136a6b>:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(n1))
<ipython-input-18-215be5136a6b>:3: RuntimeWarning: invalid value encountered in log
  print(np.log(n1))


## Copy And View

In [ ]:
import numpy as np
np1=np.array([1,2,3,4,5,6])
np2=np1.view()
print(f"Original NP1 {np1}")
print(f"Original NP2 {np2}")

np1[0]=10   # through the view command the to variable get interconnected
print(f"Original NP1 {np1}")
print(f"changed NP2 {np2}")

Original NP1 [1 2 3 4 5 6]
Original NP2 [1 2 3 4 5 6]
Original NP1 [10  2  3  4  5  6]
changed NP2 [10  2  3  4  5  6]


In [ ]:
import numpy as np
np1=np.array([1,2,3,4,5,6])
np2=np1.copy()
print(f"Original NP1 {np1}")
print(f"Original NP2 {np2}")
np1[0]=10
np2[3]=67 # np1 and np2 are completely separated
print(f"Original NP1 {np1}")
print(f"changed NP2 {np2}")

Original NP1 [1 2 3 4 5 6]
Original NP2 [1 2 3 4 5 6]
Original NP1 [10  2  3  4  5  6]
changed NP2 [ 1  2  3 67  5  6]


##  Shape and Reshape

In [ ]:
n1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(n1)
print(n1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
n2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(n2)
print(n2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [ ]:
n3=print(n1.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
n3=n1.reshape(2,3,2)  # row, row , row
print(n3)
n=n3.shape
print(n)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [ ]:
n4=n3.reshape(-1)
print(n4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Iterating through numpy

In [ ]:
import numpy as np
n1=[0,2,3,4,5,6,7,8,9,10]
np1=np.array(n1)
for i in np1:
  print(i)


0
2
3
4
5
6
7
8
9
10


In [ ]:
import numpy as np
n1=[[0,2,3,4,5],[6,7,8,9,10]]
np1=np.array(n1)
for i in np1:
  print(i )


[0 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
import numpy as np
n1=[[0,2,3,4,5],[6,7,8,9,10]]
np1=np.array(n1)
for i in np1:
  for j in i:
    print(j)


0
2
3
4
5
6
7
8
9
10


In [ ]:
n3=np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(n3.shape)
for i in n3:
  for j in i:
    for k in j:
      print(k)


(2, 2, 3)
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
n3=np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(n3):  # iterator for nth array
  print(i)


1
2
3
4
5
6
7
8
9
10
11
12


## Sorting

In [ ]:
n2=np.array(["Ayush","Hitik","Mohit","Shivam","Om","Himanshu"]) # Alphanumeric Sorting
print(n2)
print(np.sort(n2))
print(n2)

['Ayush' 'Hitik' 'Mohit' 'Shivam' 'Om' 'Himanshu']
['Ayush' 'Himanshu' 'Hitik' 'Mohit' 'Om' 'Shivam']
['Ayush' 'Hitik' 'Mohit' 'Shivam' 'Om' 'Himanshu']


In [ ]:
n2=np.array([1,5,8,6,2,0]) # numeric Sorting
print(n2)
np.sort(n2)

[1 5 8 6 2 0]


array([0, 1, 2, 5, 6, 8])

In [ ]:
n2=np.array([True, False, False, True]) # Boolean Sorting
print(n2)
np.sort(n2)

[ True False False  True]


array([False, False,  True,  True])

In [ ]:
n2=np.array([[9,8,7],[5,4,3]]) #2d Array Sorting
print(n2)
np.sort(n2)

[[9 8 7]
 [5 4 3]]


array([[7, 8, 9],
       [3, 4, 5]])

## Searching

In [ ]:
a=np.array([1,2,3,4,5,6,7])
r=np.where(a == 3)
print(r)


(array([2]),)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 2)

print(result)

(array([2, 3, 4]),)


In [ ]:
r1=np.where(a%2 == 0)
print(a[r1])

[2 4 6]


## Filtering

In [ ]:
import numpy as np
n1=np.array([1,2,3,4,5,6,7,8,9,10])
print(n1)
x=[True,True,False,False,True,False,False,True,False,False]
print(n1[x])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 5 8]


In [ ]:
fil=[]
for i in n1:
  if i%2==0:
    fil.append(True)
  else:
    fil.append(False)

print(n1)
print(fil)
print(n1[fil])

[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [ ]:
fil1 = n1%2 == 0
print(n1)
print(fil1)
print(n1[fil1])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [ ]:
fil1 = n1 >5
print(n1)
print(fil1)
print(n1[fil1])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
